<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Concerns\HasSeoMeta;
use App\Models\Concerns\HasSectionVisibility;

class AppointmentPage extends Model
{
    use HasFactory;
    use HasSeoMeta;
    use HasSectionVisibility;

    protected $fillable = [
        'hero_title',
        'hero_title_ar',
        'hero_subtitle',
        'hero_subtitle_ar',
        'hero_background_desktop',
        'hero_background_desktop_alt_en',
        'hero_background_desktop_alt_ar',
        'hero_background_mobile',
        'hero_background_mobile_alt_en',
        'hero_background_mobile_alt_ar',
        'ready_title',
        'ready_title_ar',
        'ready_description',
        'ready_description_ar',
        'ready_primary_label',
        'ready_primary_label_ar',
        'ready_primary_url',
        'ready_secondary_label',
        'ready_secondary_label_ar',
        'ready_secondary_url',
        'ready_background_image',
        'ready_background_image_alt_en',
        'ready_background_image_alt_ar',
        'step_one_label_en',
        'step_one_label_ar',
        'step_two_label_en',
        'step_two_label_ar',
        'information_title_en',
        'information_title_ar',
        'information_subtitle_en',
        'information_subtitle_ar',
        'date_time_title_en',
        'date_time_title_ar',
        'date_time_subtitle_en',
        'date_time_subtitle_ar',
        'appointment_for_label_en',
        'appointment_for_label_ar',
        'select_date_label_en',
        'select_date_label_ar',
        'select_time_label_en',
        'select_time_label_ar',
        'no_date_selected_label_en',
        'no_date_selected_label_ar',
        'full_name_label_en',
        'full_name_label_ar',
        'full_name_placeholder_en',
        'full_name_placeholder_ar',
        'email_label_en',
        'email_label_ar',
        'email_placeholder_en',
        'email_placeholder_ar',
        'company_name_label_en',
        'company_name_label_ar',
        'company_name_placeholder_en',
        'company_name_placeholder_ar',
        'user_type_label_en',
        'user_type_label_ar',
        'user_type_placeholder_en',
        'user_type_placeholder_ar',
        'user_type_options',
        'country_code_label_en',
        'country_code_label_ar',
        'phone_label_en',
        'phone_label_ar',
        'phone_placeholder_en',
        'phone_placeholder_ar',
        'message_label_en',
        'message_label_ar',
        'message_placeholder_en',
        'message_placeholder_ar',
        'continue_button_text_en',
        'continue_button_text_ar',
        'back_button_text_en',
        'back_button_text_ar',
        'book_button_text_en',
        'book_button_text_ar',
        'validation_alert_en',
        'validation_alert_ar',
        'selected_date_prefix_en',
        'selected_date_prefix_ar',
        'no_available_time_slots_text_en',
        'no_available_time_slots_text_ar',
        'loading_time_slots_text_en',
        'loading_time_slots_text_ar',
        'availability_load_error_text_en',
        'availability_load_error_text_ar',
        'past_date_validation_message_en',
        'past_date_validation_message_ar',
        'weekend_validation_message_en',
        'weekend_validation_message_ar',
        'slot_unavailable_message_en',
        'slot_unavailable_message_ar',
        'success_message_en',
        'success_message_ar',
        'weekday_labels_en',
        'weekday_labels_ar',
        'section_visibility',
    ];

    protected $casts = [
        'user_type_options' => 'array',
        'weekday_labels_en' => 'array',
        'weekday_labels_ar' => 'array',
        'section_visibility' => 'array',
    ];
}

